# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-15 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(default='4152094084@vtext.com', max_length=20)),
                ('from_address', models.CharField(default='4152094084', max_length=20)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_username', models.CharField(default='raspidispatch@gmail.com', max_length=20)),
                ('gmail_password', models.CharField(default='1121Parents1121', max_length=20)),
                ('gmail_server', models.CharField(default='smtp.gmail.com:587', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.User'),
        ),
    ]
