# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-15 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gmail_password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
