# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-15 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180515_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gmail_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail_server',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail_username',
            field=models.CharField(max_length=20),
        ),
    ]
